version: '3.8'

services:
  db:
    image: postgres:15
    container_name: splitapp_db
    environment:
      POSTGRES_DB: splitapp_db
      POSTGRES_USER: splitapp_user
      POSTGRES_PASSWORD: splitapp_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  app:
    build: .
    container_name: splitapp_api
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://splitapp_user:splitapp_password@db:5432/splitapp_db
      FLASK_ENV: development
      SESSION_SECRET: dev-secret-key
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: